import React from 'react';
import { Page, Text, View, Document, StyleSheet } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30
  },
  title: {
    fontSize: 24,
    textAlign: 'center',
    marginBottom: 20,
    color: '#123524'
  },
  section: {
    marginBottom: 20
  },
  heading: {
    fontSize: 16,
    marginBottom: 10,
    color: '#3E7B27'
  },
  table: { 
    display: "table", 
    width: "auto", 
    borderStyle: "solid", 
    borderWidth: 1, 
    borderRightWidth: 0, 
    borderBottomWidth: 0 
  },
  tableRow: { 
    margin: "auto", 
    flexDirection: "row" 
  },
  tableColHeader: { 
    width: "50%", 
    borderStyle: "solid", 
    borderWidth: 1, 
    borderLeftWidth: 0, 
    borderTopWidth: 0,
    backgroundColor: '#EFE3C2'
  },
  tableCol: { 
    width: "50%", 
    borderStyle: "solid", 
    borderWidth: 1, 
    borderLeftWidth: 0, 
    borderTopWidth: 0 
  },
  tableCellHeader: { 
    margin: 5, 
    fontSize: 12,
    fontWeight: 'bold'
  },
  tableCell: { 
    margin: 5, 
    fontSize: 10 
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 0,
    right: 0,
    textAlign: 'center',
    fontSize: 10,
    color: '#666'
  }
});

const ExpenseReportPDF = ({ data }) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <Text style={styles.title}>FareFlow Expense Report</Text>
      
      <View style={styles.section}>
        <Text style={styles.heading}>Summary Statistics</Text>
        <View style={styles.table}>
          {data.slice(0, 6).map((row, i) => (
            <View style={styles.tableRow} key={i}>
              <View style={styles.tableColHeader}>
                <Text style={styles.tableCellHeader}>{row[0]}</Text>
              </View>
              <View style={styles.tableCol}>
                <Text style={styles.tableCell}>{row[1]}</Text>
              </View>
            </View>
          ))}
        </View>
      </View>
      
      <View style={styles.section}>
        <Text style={styles.heading}>Weekly Breakdown</Text>
        <View style={styles.table}>
          {data.slice(7, 15).map((row, i) => (
            <View style={styles.tableRow} key={i}>
              <View style={styles.tableColHeader}>
                <Text style={styles.tableCellHeader}>{row[0]}</Text>
              </View>
              <View style={styles.tableCol}>
                <Text style={styles.tableCell}>{row[1]}</Text>
              </View>
            </View>
          ))}
        </View>
      </View>
      
      <View style={styles.section}>
        <Text style={styles.heading}>Monthly Breakdown</Text>
        <View style={styles.table}>
          {data.slice(16).map((row, i) => (
            <View style={styles.tableRow} key={i}>
              <View style={styles.tableColHeader}>
                <Text style={styles.tableCellHeader}>{row[0]}</Text>
              </View>
              <View style={styles.tableCol}>
                <Text style={styles.tableCell}>{row[1]}</Text>
              </View>
            </View>
          ))}
        </View>
      </View>
      
      <Text style={styles.footer}>
        Generated by FareFlow on {new Date().toLocaleDateString()}
      </Text>
    </Page>
  </Document>
);

export default ExpenseReportPDF;